version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'playwright'
    commit-message:
      prefix: 'chore:'
      prefix-development: 'chore: '
    rebase-strategy: 'disabled'
    reviewers:
      - 'laodeaksarr'
    open-pull-requests-limit: 10
